"""initial ledger

Creates the five append-only ledger tables (forecasts, observations,
calibration_params, market_snapshots, fills), their ``ix_<table>_latest`` indexes, and
the append-only enforcement (D-10): a shared ``raise_append_only`` function plus a pair
of ON UPDATE / ON DELETE rules per table that turn any mutation into an error. This
mirrors the DDL-event guards on ``weatherquant.db.models.metadata`` so the migrated
schema is identical to ``metadata.create_all`` — corrections are new INSERTs with a
later ``available_at``, never UPDATE/DELETE (threat T-01-07).

Revision ID: 0001
Revises:
Create Date: 2026-06-15 13:45:03.688515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Append-only enforcement DDL is single-sourced in weatherquant.db.ddl; this migration
# and weatherquant.db.models both consume it, so the migrated schema and the
# metadata.create_all schema cannot drift apart.
from weatherquant.db import ddl


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _install_append_only_guards() -> None:
    """Create the raise trigger function + per-table triggers (D-10), from ddl.py."""
    op.execute(ddl.CREATE_RAISE_FUNCTION_SQL)
    for name in ddl.LEDGER_TABLES:
        for stmt in ddl.create_trigger_sql(name):
            op.execute(stmt)


def _remove_append_only_guards() -> None:
    """Drop the triggers + trigger function (inverse of the install helper)."""
    for name in ddl.LEDGER_TABLES:
        for stmt in ddl.drop_trigger_sql(name):
            op.execute(stmt)
    op.execute(ddl.DROP_RAISE_FUNCTION_SQL)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_params',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('lead', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calibration_params_latest', 'calibration_params', ['city', 'model', 'lead', 'month', 'available_at'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('trade_id', sa.Text(), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fills_latest', 'fills', ['ticker', 'trade_id', 'available_at'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('lead', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecasts_latest', 'forecasts', ['city', 'target_date', 'model', 'lead', 'available_at'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('snapshot_for', sa.Text(), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_snapshots_latest', 'market_snapshots', ['ticker', 'snapshot_for', 'available_at'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_observations_latest', 'observations', ['city', 'target_date', 'source', 'available_at'], unique=False)
    # ### end Alembic commands ###

    # Append-only enforcement (D-10) — hand-added; rules/functions are not reflectable
    # by autogenerate, so they live here to keep the migrated schema insert-only.
    _install_append_only_guards()


def downgrade() -> None:
    """Downgrade schema."""
    # Drop append-only guards first (rules depend on the tables / the raise helper).
    _remove_append_only_guards()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_observations_latest', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_market_snapshots_latest', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index('ix_forecasts_latest', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index('ix_fills_latest', table_name='fills')
    op.drop_table('fills')
    op.drop_index('ix_calibration_params_latest', table_name='calibration_params')
    op.drop_table('calibration_params')
    # ### end Alembic commands ###
